version: '3'

services:

    app:
        build:
            context: ./docker/app
        image: app
        container_name: app
        hostname: kma
        volumes:
            - ./:/app
        depends_on:
            - mariadb
            - rabbitmq
#            - clickhouse
        env_file:
            - .env
        ports:
            - ${APP_PORT}:8000

    mariadb:
        image: mariadb:10.11.3
        container_name: mariadb
        hostname: mariadb
        environment:
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MYSQL_USER: ${MARIADB_USERNAME}
            MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
            MYSQL_PASSWORD: ${MARIADB_PASSWORD}
        ports:
            - ${MARIADB_PORT}:3306
        volumes:
            - ./docker/storages/mariadb:/var/lib/mysql
            - ./docker/mariadb/init/:/docker-entrypoint-initdb.d

    rabbitmq:
        image: rabbitmq:3.12.4-management
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - ${RABBITMQ_AMQP_PORT}:5672
            - ${RABBITMQ_UI_PORT}:15672
        volumes:
            - ./docker/storages/rabbitmq:/var/lib/rabbitmq/mnesia
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}


    clickhouse:
        image: yandex/clickhouse-server
        container_name: clickhouse
        ports:
            - "8123:8123" # HTTP-порт для обработки запросов
            - "9000:9000" # Native-порт для клиентов ClickHouse
            - "9009:9009" # Native-порт для репликации
        volumes:
            - ./docker/storages/clickhouse:/var/lib/clickhouse
#            - /path/to/clickhouse-config:/etc/clickhouse-server
        environment:
            - CLICKHOUSE_PASSWORD=my_password
#        networks:
#            - clickhouse-network
#
#networks:
#    clickhouse-network:
