version: '3'

services:

    app:
        build:
            context: ./docker/app
        image: app
        container_name: app
        hostname: kma
        volumes:
            - ./:/app
        depends_on:
            - mariadb
            - rabbitmq

        env_file:
            - .env
#        environment:
#            DB_HOST: mariadb
#            DB_PORT: 3306
#            DB_DATABASE: ${MARIADB_DATABASE}
#            DB_USERNAME: ${MARIADB_USERNAME}
#            DB_PASSWORD: ${MARIADB_PASSWORD}
#            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
#            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - ${APP_PORT}:8000
        # command: sh -c "composer install"

    mariadb:
        image: mariadb:10.11.3
        container_name: mariadb
        hostname: mariadb
        environment:
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MYSQL_USER: ${MARIADB_USERNAME}
            MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
            MYSQL_PASSWORD: ${MARIADB_PASSWORD}
        ports:
            - ${MARIADB_PORT}:3306
        volumes:
            - ./docker/storages/mariadb:/var/lib/mysql
            - ./docker/mariadb/init/:/docker-entrypoint-initdb.d



    rabbitmq:
        image: rabbitmq:3.12.4-management
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - ${RABBITMQ_AMQP_PORT}:5672
            - ${RABBITMQ_UI_PORT}:15672
        volumes:
            - ./docker/storages/rabbitmq:/var/lib/rabbitmq/mnesia

        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

#            RABBITMQ_ERLANG_COOKIE: "qwerty12"  # cookie для Erlang
#            RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password



#

#




