version: '3'

services:

    app:
        build:
            context: ./docker/app
        image: app
        container_name: app
        hostname: app
        volumes:
            - ./:/app
        depends_on:
            - mariadb
            - rabbitmq
            - clickhouse
        env_file:
            - .env

    rabbitmq:
        image: rabbitmq:3.12.4-management
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - ${RABBITMQ_UI_HOST_PORT}:15672
        volumes:
            - ./docker/storages/rabbitmq:/var/lib/rabbitmq/mnesia
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}


    mariadb:
        image: mariadb:10.11.3
        container_name: mariadb
        hostname: mariadb
        environment:
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MYSQL_USER: ${MARIADB_USERNAME}
            MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
            MYSQL_PASSWORD: ${MARIADB_PASSWORD}
        ports:
            - ${MARIADB_HOST_PORT}:3306
        volumes:
            - ./docker/storages/mariadb:/var/lib/mysql
            - ./docker/mariadb/init/:/docker-entrypoint-initdb.d

    clickhouse:
        image: yandex/clickhouse-server
        container_name: clickhouse
        hostname: clickhouse
        ports:
            - ${CLICKHOUSE_HOST_HTTP_PORT}:8123
        volumes:
            - ./docker/storages/clickhouse:/var/lib/clickhouse
            - ./docker/clickhouse/init/:/docker-entrypoint-initdb.d
        environment:
            CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
            CLICKHOUSE_USER: ${CLICKHOUSE_USER}
            CLICKHOUSE_DB: ${CLICKHOUSE_DB}




